import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ContactList } from "./page";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex flex-row w-screen h-screen overflow-hidden gap-5" suppressHydrationWarning>
          <ContactList />
          {children}
        </div>
      </body>
    </html>
  );
}
